// src/lib/components/SplitGrid.svelte
<script lang="ts">
  import { listenForSplitAdded, listenForTrackAdded } from "@lib/backend";
  import type { AlignmentTrackData, SplitData } from "@lib/bindings";
  import RefSeqArea from "@lib/components/RefSeqArea.svelte";
  import type { DividerDragHandler } from "@lib/components/SplitGrid.types";
  import type { SplitState, TrackState } from "@lib/components/SplitGrid.types";
  import SplitToolbar from "@lib/components/SplitToolbar.svelte";
  import TrackArea from "@lib/components/TrackArea.svelte";
  import { DIVIDER_PX } from "@lib/constants";
  import { loadPixiAssets } from "@lib/drawing";
  import LOG from "@lib/logger";
  import { sum } from "@lib/util";
  import { SvelteComponent, afterUpdate, onMount } from "svelte";

  // Minimum size that a split or track can be resized as percent of the split grid
  const minCellPct = 2;

  let trackArea: SvelteComponent;
  let splits: SplitState[] = [];
  let tracks: TrackState[] = [];
  let trackAreaHeight: number;
  let gridWidth: number;
  let offsetTop: number;
  let offsetLeft: number;
  let assetsLoaded: boolean = false;

  onMount(async () => {
    loadPixiAssets().load(() => {
      assetsLoaded = true;
    });
  });

  const handleNewTrack = (newTrack: AlignmentTrackData): void => {
    LOG.debug(`Handling track-added event: ${JSON.stringify(newTrack)}`);
    const numTracks = tracks.length;
    const newTrackHeight = 100 / (numTracks + 1);
    tracks.map((track) => {
      track.heightPct = track.heightPct - newTrackHeight / numTracks;
    });
    const newTrackState: TrackState = {
      ...newTrack,
      heightPct: newTrackHeight,
    };
    tracks = [...tracks, newTrackState];
    LOG.debug(`Updating UI with new track: ${JSON.stringify(newTrackState)}`);
  };

  const handleNewSplit = (newSplit: SplitData): void => {
    LOG.debug(`Handling spit-added event: ${JSON.stringify(newSplit)}`);
    const numSplits = splits.length;
    const newSplitWidth = 100 / (numSplits + 1);
    splits.map((split) => {
      split.widthPct = split.widthPct - newSplitWidth / numSplits;
    });
    const newSplitState: SplitState = {
      id: newSplit.id,
      widthPct: newSplitWidth,
      focusedRegion: newSplit.focusedRegion,
    };
    LOG.debug(`Updating UI with new split: ${JSON.stringify(newSplitState)}`);
    splits = [...splits, newSplitState];
  };

  const adjustDimensions = ({
    currentDimensions,
    dividerIndex,
    mousePosPct,
  }: {
    readonly currentDimensions: number[];
    dividerIndex: number;
    mousePosPct: number;
  }): number[] => {
    // E.g start with 33%, 33%, 33%
    // Divider 0 moved to 10%
    // Set track 0 to 10%
    // Set other tracks to (33 - 23/2)%
    //
    // Calculate a cumulative sum of the splits/tracks up to the current one. This is used to
    // determine where the mouse is in relation to the current split/track.
    const cumSumDim = sum(currentDimensions.slice(0, dividerIndex + 1));
    let diff = mousePosPct - cumSumDim + (DIVIDER_PX / window.innerHeight) * 100;
    if (currentDimensions[dividerIndex] + diff < minCellPct) {
      diff = minCellPct - currentDimensions[dividerIndex];
    } else if (currentDimensions[dividerIndex + 1] - diff < minCellPct) {
      diff = currentDimensions[dividerIndex + 1] - minCellPct;
    }
    const updatedDimensions = Array.from(
      currentDimensions.map((dim, dimIndex) => {
        if (dimIndex === dividerIndex) {
          return dim + diff;
        } else if (dimIndex === dividerIndex + 1) {
          return dim - diff;
        } else {
          return dim;
        }
      })
    );
    return updatedDimensions;
  };

  const getMouseYPosPct = (mouseYPos: number) => {
    return ((mouseYPos - offsetTop) / trackAreaHeight) * 100;
  };

  const getMouseXPosPct = (mouseXPos: number) => {
    return ((mouseXPos - offsetLeft) / gridWidth) * 100;
  };

  const setSplitWidths = (widths: readonly number[]): void => {
    splits.map((split, index) => {
      split.widthPct = widths[index];
    });
    splits = splits;
  };

  const setTrackHeights = (heights: readonly number[]): void => {
    tracks.map((track, index) => {
      track.heightPct = heights[index];
    });
    tracks = tracks;
  };

  const handleHorizontalDividerDrag: DividerDragHandler = ({ mouseEvent, dividerIndex }) => {
    const mouseYPos = mouseEvent.clientY;
    const mousePosPct = getMouseYPosPct(mouseYPos);
    const currentDimensions = Array.from(tracks.map((track) => track.heightPct));
    const updatedTrackHeights = adjustDimensions({
      mousePosPct,
      dividerIndex,
      currentDimensions,
    });
    LOG.debug(
      `Handling divider drag event: mousePos=${mouseYPos}; ` +
        `windowHeight=${window.innerHeight}; mousePosPct=${mousePosPct}; ` +
        `initialTrackHeights=${currentDimensions} updatedTrackHeights=${updatedTrackHeights}`
    );
    setTrackHeights(updatedTrackHeights);
  };

  const handleVerticalDividerDrag: DividerDragHandler = ({ mouseEvent, dividerIndex }) => {
    const mouseXPos = mouseEvent.clientX;
    const mousePosPct = getMouseXPosPct(mouseXPos);
    // const mousePosPct = (mouseXPos / window.innerWidth) * 100;
    const currentDimensions = Array.from(splits.map((split) => split.widthPct));
    const updatedSplitWidths = adjustDimensions({
      mousePosPct,
      dividerIndex,
      currentDimensions,
    });
    LOG.debug(
      `Handling divider drag event: mousePos=${mouseXPos}; ` +
        `windowWidth=${window.innerWidth}; mousePosPct=${mousePosPct}; ` +
        `initialSplitWidths=${currentDimensions} updatedSplitWidths=${updatedSplitWidths}`
    );
    setSplitWidths(updatedSplitWidths);
  };

  afterUpdate(() => {
    if (trackArea !== undefined) {
      gridWidth = trackArea.offsetWidth;
      trackAreaHeight = trackArea.offsetHeight;
      offsetLeft = trackArea.offsetLeft;
      offsetTop = trackArea.offsetTop;
    }
  });

  listenForSplitAdded((event) => handleNewSplit(event.payload));
  listenForTrackAdded((event) => handleNewTrack(event.payload));
</script>

<div class="split-grid">
  {#if assetsLoaded}
    <SplitToolbar {splits} {handleVerticalDividerDrag} />
    <RefSeqArea {splits} {handleVerticalDividerDrag} />
    <TrackArea
      bind:this={trackArea}
      {tracks}
      {splits}
      {handleHorizontalDividerDrag}
      {handleVerticalDividerDrag}
    />
  {/if}
</div>

<style>
  .split-grid {
    display: flex;
    flex-grow: 1;
    flex-direction: column;
    width: 100%;
  }
</style>

// frontend/components/SplitGrid.tsx
import { Box, Flex } from "@chakra-ui/react";
import { ReactElement, useEffect, useRef, useState } from "react";

import { AlignmentTrackData } from "../bindings";
import { SplitData } from "../bindings";
import { listenForSplitAdded, listenForTrackAdded } from "../lib/backend";
import { DIVIDER_PX } from "../lib/constants";
import { loadPixiAssets } from "../lib/drawing";
import { useBackendListener } from "../lib/hooks";
import LOG from "../lib/logger";
import { Size } from "../lib/types";
import ErrorBoundary from "./ErrorBoundary";
import { GridDivider } from "./GridDivider";
import RefSeqArea from "./RefSeqArea";
import SplitToolbar from "./SplitToolbar";
import Track, { SplitState } from "./Track";

const REF_SEQ_HEIGHT = "24px";
const SPLIT_TOOLBAR_HEIGHT = "50px";

interface TrackState {
  id: string;
  heightPct: number;
  name: string;
}

const SplitGrid = ({ height, width }: { height: Size; width: Size }): ReactElement => {
  const ref = useRef<HTMLDivElement>(null);
  const [assetsLoaded, setAssetsLoaded] = useState(false);
  const [tracks, setTracks] = useState<TrackState[]>([]);
  const [splits, setSplits] = useState<SplitState[]>([]);

  useEffect(() => {
    loadPixiAssets().load(() => setAssetsLoaded(true));
  }, []);

  const addTrack = (newTrack: AlignmentTrackData): void => {
    LOG.debug(`Handling track-added event: ${JSON.stringify(newTrack)}`);
    setTracks((state) => {
      LOG.debug("setTracks called...");
      const numTracks = state.length;
      const newTrackHeight = 100 / (numTracks + 1);
      state.map((track) => {
        track.heightPct = track.heightPct - newTrackHeight / numTracks;
      });
      const newTrackState: TrackState = {
        ...newTrack,
        heightPct: newTrackHeight,
      };
      state.push(newTrackState);
      LOG.debug(`Updating UI with new track: ${JSON.stringify(newTrackState)}`);
      return [...state];
    });
  };

  const addSplit = (newSplit: SplitData): void => {
    setSplits((state) => {
      LOG.debug(`Handling spit-added event: ${JSON.stringify(newSplit)}`);
      const numSplits = state.length;
      const newSplitWidth = 100 / (numSplits + 1);
      state.map((split) => {
        split.widthPct = split.widthPct - newSplitWidth / numSplits;
      });
      const newSplitState: SplitState = {
        id: newSplit.id,
        widthPct: newSplitWidth,
        focusedRegion: newSplit.focusedRegion,
      };
      LOG.debug(`Updating UI with new split: ${JSON.stringify(newSplitState)}`);
      state.push(newSplitState);
      return [...state];
    });
  };

  useBackendListener(listenForTrackAdded, (event) => addTrack(event.payload));
  useBackendListener(listenForSplitAdded, (event) => addSplit(event.payload));

  return (
    <>
      {assetsLoaded && (
        <Box className="split-grid" ref={ref} height={height} width={width}>
          <RefSeqArea height={REF_SEQ_HEIGHT} width="full" splitGridRef={ref} />
          <Flex width="full" height={SPLIT_TOOLBAR_HEIGHT} flexDirection="row" alignItems="center">
            {splits.map((split) => (
              <SplitToolbar split={split} key={split.id} />
            ))}
          </Flex>
          <Flex
            className="tracks"
            style={{ height: `calc(100% - ${REF_SEQ_HEIGHT} - ${SPLIT_TOOLBAR_HEIGHT})` }}
            width="full"
            flexDirection="column"
          >
            {tracks.map((track, trackIndex: number) => {
              return (
                <ErrorBoundary key={trackIndex}>
                  <Track
                    trackData={track}
                    height={`${track.heightPct}%`}
                    width="full"
                    splitGridRef={ref}
                    splits={splits}
                  ></Track>
                  {trackIndex != tracks.length - 1 && (
                    <GridDivider
                      height={`${DIVIDER_PX}px`}
                      width="full"
                      index={trackIndex}
                      orientation="horizontal"
                      splitGridRef={ref}
                    />
                  )}
                </ErrorBoundary>
              );
            })}
          </Flex>
        </Box>
      )}
    </>
  );
};

export default SplitGrid;
