// src/lib/components/Track.svelte
<script lang="ts">
  import AlignmentsView from "@lib/components/AlignmentsView.svelte";
  import GridDivider from "@lib/components/GridDivider.svelte";
  import type { DividerDragHandler, SplitState } from "@lib/components/SplitGrid.types";

  export let name: string;
  export let id: string;
  export let heightPct: number;
  export let splits: SplitState[];
  export let handleVerticalDividerDrag: DividerDragHandler;
</script>

<div class="track" style:height={`${heightPct}%`}>
  <div class="track-label">
    {name}
  </div>
  <div class="split-container">
    {#each splits as split, splitIndex}
      <AlignmentsView trackId={id} splitId={split.id} widthPct={split.widthPct} />
      {#if splitIndex < splits.length}
        <GridDivider
          orientation="vertical"
          dragHandler={(mouseEvent) =>
            handleVerticalDividerDrag({ mouseEvent, dividerIndex: splitIndex })}
        />
      {/if}
    {/each}
  </div>
</div>

<style>
  .track {
    display: flex;
    flex-direction: column;
    width: 100%;
  }

  .track-label {
    background-color: var(--color-trackLabelBackground);
    font-size: 12px;
    color: var(--color-secondaryText);
    width: 100%;
  }

  .split-container {
    display: flex;
    flex-direction: row;
    width: 100%;
    flex-grow: 1;
  }
</style>

// frontend/components/Track.tsx
import { Box, Flex, HStack, Text } from "@chakra-ui/react";
import { ReactElement, RefObject, useContext, useState } from "react";

import { GenomicRegion } from "../bindings";
import { TrackState } from "../contexts/SplitGridContext";
import { DIVIDER_PX } from "../lib/constants";
import { Size } from "../lib/types";
import AlignmentsView from "./AlignmentsView";
import ErrorBoundary from "./ErrorBoundary";
import { GridDivider } from "./GridDivider";

const TRACK_LABEL_HEIGHT = "34px";

export interface SplitState {
  id: string;
  widthPct: number;
  focusedRegion: GenomicRegion | null;
}

const Track = <T extends HTMLElement>({
  height,
  width,
  trackData,
  splitGridRef,
  splits,
}: {
  height: Size;
  width: Size;
  readonly trackData: TrackState;
  readonly splitGridRef: RefObject<T>;
  readonly splits: SplitState[];
}): ReactElement => {
  return (
    <Flex className="track" height={height} width={width} flexDirection="column">
      <Box
        className="track-label"
        height={`${TRACK_LABEL_HEIGHT}`}
        width="full"
        fontSize="12px"
        backgroundColor="brand.trackLabelBackground"
      >
        <Text color="brand.secondaryText">{trackData.name}</Text>
      </Box>
      <Flex
        className="split-container"
        flexDirection="row"
        style={{ height: `calc(100% - ${TRACK_LABEL_HEIGHT})` }}
      >
        {splits.map((split, splitIndex: number) => {
          return (
            <ErrorBoundary key={splitIndex}>
              <HStack className="split" spacing="0px" height="full" width={`${split.widthPct}%`}>
                <AlignmentsView
                  trackId={trackData.id}
                  splitId={split.id}
                  style={{ width: `calc(100% - ${DIVIDER_PX}px)` }}
                  height="full"
                />
                {splitIndex != splits.length - 1 && (
                  <GridDivider
                    height="full"
                    width={`${DIVIDER_PX}px`}
                    orientation={"vertical"}
                    index={splitIndex}
                    splitGridRef={splitGridRef}
                  />
                )}
              </HStack>
            </ErrorBoundary>
          );
        })}
      </Flex>
    </Flex>
  );
};

export default Track;
