// frontend/components/RefSeqView.tsx
import { Box } from "@chakra-ui/react";
import * as PIXI from "pixi.js";
import { ReactElement, useContext, useEffect, useRef } from "react";

import { NucleotideColorConfig } from "../bindings";
import { RefSeqContext } from "../contexts/RefSeqContext";
import { UserConfigContext } from "../contexts/UserConfigContext";
import { PRIMARY_IUPAC_NUCLEOTIDES, SECONDARY_IUPAC_NUCLEOTIDES } from "../lib/constants";
import {
  DRAW_LETTER_THRESHOLD,
  DrawConfig,
  StageManager,
  drawRect,
  drawText,
} from "../lib/drawing";
import { getLength } from "../lib/genomicCoordinates";
import { useElementSize, usePixiApp, usePixiStage } from "../lib/hooks";
import LOG from "../lib/logger";
import { IUPACNucleotide, Size } from "../lib/types";

const RefSeqView = ({
  height,
  width,
  splitId,
}: {
  height: Size;
  width: Size;
  splitId: string;
}): ReactElement => {
  const refSeqContext = useContext(RefSeqContext);
  const userConfigContext = useContext(UserConfigContext);
  const ref = useElementSize<HTMLDivElement>();
  const pixiApp = usePixiApp({ ref });

  const initStageManager = (): StageManager => {
    const drawConfig: DrawConfig = {};
    PRIMARY_IUPAC_NUCLEOTIDES.forEach((nuc) => {
      const nucColor = userConfigContext.styles.colors.nucleotideColors[nuc];
      drawConfig[nuc + "Rect"] = {
        drawFn: () =>
          drawRect({
            color: nucColor,
            dim: { width: 10, height: 20 },
          }),
        poolsize: 1000,
      };
      drawConfig[nuc + "Text"] = {
        drawFn: () => drawText({ content: nuc, style: { tint: nucColor } }),
        poolsize: 100,
      };
    });
    SECONDARY_IUPAC_NUCLEOTIDES.forEach((nuc) => {
      const nucColor = userConfigContext.styles.colors.nucleotideColors[nuc];
      drawConfig[nuc + "Rect"] = {
        drawFn: () =>
          drawRect({
            color: nucColor,
            dim: { width: 10, height: 20 },
          }),
        poolsize: 10,
      };
      drawConfig[nuc + "Text"] = {
        drawFn: () => drawText({ content: nuc, style: { tint: nucColor } }),
        poolsize: 10,
      };
    });
    return new StageManager({ drawConfig, stage: pixiApp.stage });
  };

  const stageManager = useRef(initStageManager());

  const draw = () => {
    LOG.debug("Redrawing RefSeqView...");
    if (ref.current === null) {
      return;
    }
    stageManager.current.recycleAll();
    pixiApp.resize(ref.current.offsetWidth, ref.current.offsetHeight);
    const splitContext = refSeqContext[splitId];
    if (splitContext.focusedRegion === null) {
      LOG.debug("Null focusedRegion in RefSeqView...");
      return;
    }

    const numNucs = Number(getLength(splitContext.focusedRegion));

    if (numNucs > 10000) {
      return;
    }

    const nucWidth = ref.current.offsetWidth / numNucs;
    LOG.debug(
      `Redrawing RefSeqView with nucWidth=${nucWidth}, numNucs=${numNucs}, region=${JSON.stringify(
        splitContext.focusedRegion
      )}, width=${ref.current.offsetWidth}, height=${ref.current.offsetHeight}`
    );
    for (let i = 0; i < getLength(splitContext.focusedRegion); i++) {
      let nuc = splitContext.sequence.charAt(i);
      nuc = nuc !== "-" ? nuc : "GAP";
      const x = i * nucWidth;
      if (nucWidth > DRAW_LETTER_THRESHOLD) {
        stageManager.current.draw(nuc + "Text", {
          pos: { x, y: 0 },
        });
      } else {
        stageManager.current.draw(nuc + "Rect", {
          pos: { x, y: 0 },
          dim: { width: nucWidth, height: ref.current.offsetHeight },
        });
      }
    }
  };

  usePixiStage({ ref, draw });

  return <Box className="ref-seq" ref={ref} height={height} width={width}></Box>;
};

export default RefSeqView;

// src/lib/components/RefSeqView.svelte
<script lang="ts">
  import { getFocusedSequence, listenForFocusedSequenceUpdated } from "@lib/backend";
  import type { FocusedSequenceUpdatedPayload } from "@lib/bindings";
  import { PRIMARY_IUPAC_NUCLEOTIDES, SECONDARY_IUPAC_NUCLEOTIDES } from "@lib/constants";
  import {
    DRAW_LETTER_THRESHOLD,
    DrawPoolGroup,
    PixiApplication,
    drawRect,
    drawText,
  } from "@lib/drawing/drawing";
  import type { DrawConfig } from "@lib/drawing/drawing";
  import LOG from "@lib/logger";
  import { USER_CONFIG_STORE } from "@lib/stores/UserConfigStore";
  import { onDestroy, onMount } from "svelte";

  export let splitId: string;
  export let widthPct: number;

  let canvasWidth: number;
  let canvasHeight: number;
  let canvas: HTMLDivElement;
  let drawPool: DrawPoolGroup | null = null;
  let sequence: string | null;
  const pixiApp = new PixiApplication();

  $: nucleotideColors = $USER_CONFIG_STORE!.styles.colors.nucleotideColors;
  $: canvasWidth, sequence, draw();

  const handleFocusedSequenceUpdated = (payload: FocusedSequenceUpdatedPayload): void => {
    if (payload.splitId === splitId) {
      console.log("Handling sequence update...");
      sequence = payload.sequence;
    }
  };

  const initPixiRenderer = (stage: Element): void => {
    pixiApp.resize({ width: canvasWidth, height: canvasHeight });
    stage.appendChild(pixiApp.renderer.view as HTMLCanvasElement);
  };

  const initStageManager = (): DrawPoolGroup => {
    const drawConfig: DrawConfig = {};
    PRIMARY_IUPAC_NUCLEOTIDES.forEach((nuc) => {
      const nucColor = nucleotideColors[nuc];
      drawConfig[nuc + "Rect"] = {
        drawFn: () =>
          drawRect({
            color: nucColor,
            dim: { width: 10, height: 15 },
          }),
        poolsize: 1000,
      };
      drawConfig[nuc + "Text"] = {
        drawFn: () => drawText({ content: nuc, style: { tint: nucColor, fontSize: 15 } }),
        poolsize: 100,
      };
    });
    SECONDARY_IUPAC_NUCLEOTIDES.forEach((nuc) => {
      const nucColor = nucleotideColors[nuc];
      drawConfig[nuc + "Rect"] = {
        drawFn: () =>
          drawRect({
            color: nucColor,
            dim: { width: 10, height: 20 },
          }),
        poolsize: 10,
      };
      drawConfig[nuc + "Text"] = {
        drawFn: () => drawText({ content: nuc, style: { tint: nucColor, fontSize: 15 } }),
        poolsize: 10,
      };
    });
    return new DrawPoolGroup({ drawConfig, stage: pixiApp.stage });
  };

  const draw = () => {
    if (drawPool === null) {
      return;
    }
    LOG.debug("Redrawing RefSeqView...");
    drawPool.recycleAll();
    pixiApp.resize({ width: canvasWidth, height: canvasHeight });

    if (sequence === null) {
      return;
    }

    const nucWidth = canvasWidth / sequence.length;
    LOG.debug(
      `Redrawing RefSeqView with nucWidth=${nucWidth}, sequence.length=${sequence.length}, width=${canvasWidth}, height=${canvasHeight}`
    );
    for (let i = 0; i < sequence.length; i++) {
      let nuc = sequence.charAt(i);
      nuc = nuc !== "-" ? nuc : "GAP";
      const x = i * nucWidth;
      if (nucWidth > DRAW_LETTER_THRESHOLD) {
        drawPool.draw(nuc + "Text", {
          pos: { x, y: 0 },
        });
      } else {
        drawPool.draw(nuc + "Rect", {
          pos: { x, y: 0 },
          dim: { width: nucWidth, height: canvasHeight },
        });
      }
    }
  };

  onMount(async () => {
    getFocusedSequence(splitId).then((focusedSequence) => {
      initPixiRenderer(canvas);
      drawPool = initStageManager();
      sequence = focusedSequence;
      draw();
    });
  });

  onDestroy(async () => {
    pixiApp.destroy();
    LOG.debug("Destroyed RefSeqView PIXI application");
  });

  listenForFocusedSequenceUpdated((event) => handleFocusedSequenceUpdated(event.payload));
</script>

<div style:width={`${widthPct}%`} bind:offsetHeight={canvasHeight} bind:offsetWidth={canvasWidth}>
  <div bind:this={canvas} />
</div>
