// frontend/components/Toolbar.tsx
import { Button, Flex } from "@chakra-ui/react";
import { ReactElement, useContext } from "react";

import { AlertApiContext } from "../contexts/AlertContext";
import { addAlignmentTrack, addSplit, openFileDialog } from "../lib/backend";
import LOG from "../lib/logger";
import { Size } from "../lib/types";

const Toolbar = ({ height, width }: { height: Size; width: Size }): ReactElement => {
  const alertApi = useContext(AlertApiContext);

  const newTrack = () => {
    openFileDialog()
      .then((fileNames) => {
        if (fileNames === null) {
          return;
        }
        fileNames.map((fileName) =>
          addAlignmentTrack({ bamPath: fileName }).catch((error) => {
            alertApi.addAlert({ message: error, status: "error" });
            LOG.error(error);
          })
        );
      })
      .catch((error) => {
        alertApi.addAlert({ message: "Failed to open file picker dialog", status: "error" });
        LOG.error(error);
      });
  };

  const newSplit = (): void => {
    addSplit({
      focusedRegion: null,
    }).catch((error) => {
      alertApi.addAlert({ message: error, status: "error" });
      LOG.error(error);
    });
  };

  return (
    <Flex className="toolbar" height={height} width={width} flexDirection="column">
      <Flex width="full" height="full" flexDirection="row">
        <Button size="sm" onClick={() => newTrack()}>
          Add Track
        </Button>
        <Button size="sm" onClick={() => newSplit()}>
          Add Split
        </Button>
      </Flex>
    </Flex>
  );
};

export default Toolbar;

// src/lib/components/Toolbar.svelte
<script lang="ts">
  import { addAlignmentTrack, addSplit, openFileDialog } from "@lib/backend";
  import Button from "@lib/components/Button.svelte";
  import { defaultErrorHandler } from "@lib/errorHandling";
  import LOG from "@lib/logger";

  const newTrack = () => {
    LOG.info("Adding new track...");
    openFileDialog()
      .then((fileNames) => {
        if (fileNames === null) {
          return;
        }
        fileNames.map((fileName) =>
          addAlignmentTrack({ bamPath: fileName }).catch(defaultErrorHandler)
        );
      })
      .catch((error) => defaultErrorHandler(error, "Failed to open file picker dialog"));
  };

  const newSplit = (): void => {
    LOG.info("Adding new split...");
    addSplit({
      focusedRegion: null,
    }).catch(defaultErrorHandler);
  };
</script>

<div style:display="flex">
  <Button class="btn-sm" on:click={newTrack}>Add Track</Button>
  <Button class="btn-sm" on:click={newSplit}>Add Split</Button>
</div>
